env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "fast-web-419215-35d284e06546.json"

runtime: nodejs16
handlers:
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /.*
  static_files: build/index.html
  upload: build/index.html

instance_class: F4


# Specify the maximum number of instances
automatic_scaling:
  max_instances: 1